### ISSUE TITLE
[RequiredMember] Attribute Not Found

### ISSUE THREAD

**Issue by adampsst** [dre0dru/AddressablesServices#1]
When installing within a project using Unity 2020.1.17f1, we get an error relating to [RequiredMember] attribute is not found. It looks like you support 2020.1 and above according to the docs but its throwing this error?

**Comment by dre0dru** [comment]
My bad, I thought this attribute was introduced in 2020.1+
Will fix it today

**Comment by dre0dru** [comment]
Done in [commit](https://github.com/dre0dru/AddressablesServices/commit/9c227859da01e00714bc454a3a3d00f29c330764)
