### ISSUE TITLE
Missing asmdef when used with Shared.Sources

### ISSUE THREAD

**Issue by GyGerg** [dre0dru/AddressablesServices#2]
Half-related to SharedSources, TMPBuildProcessorSettings can't find Shared.Sources.CustomDrawers because of a missing assembly reference. (Might've been broken since SharedResources' 2.6.1 update

Error(s) are the following:
- Library/PackageCache/com.dre0dru.addressables.services@b447dabe37/Editor/Fonts/TMPBuildProcessorSettings.cs(3,22): error CS0234: The type or namespace name 'CustomDrawers' does not exist in the namespace 'Shared.Sources' (are you missing an assembly reference?)

Followed by 4 FolderReference errors in the same file

**Comment by dre0dru** [comment]
@GyGerg thanks for notice! 
Fixed in next [release](https://github.com/dre0dru/AddressablesServices/releases/tag/v6.1.1).
