### ISSUE TITLE
EditorExtensions,Collections,UDictionarySo,FolderReference could not be found

### ISSUE THREAD

**Issue by williamlv** [dre0dru/AddressablesServices#3]
Editor/RuntimeAssets/AssetsScannerComposite.cs(2,15): error CS0234: The type or namespace name 'EditorExtensions' does not exist in the namespace 'Dre0Dru' (are you missing an assembly reference?)
Editor/RuntimeAssets/ScannerTarget.cs(2,15): error CS0234: The type or namespace name 'Collections' does not exist in the namespace 'Dre0Dru' (are you missing an assembly reference?)
Editor/RuntimeAssets/ScannerTarget.cs(12,16): error CS0246: The type or namespace name 'UDictionarySo<,>' could not be found (are you missing a using directive or an assembly reference?)
Editor/RuntimeAssets/ScannerTarget.cs(15,16): error CS0246: The type or namespace name 'FolderReference' could not be found (are you missing a using directive or an assembly reference?)

**Comment by deniskutovskiy** [comment]
Found the necessary packages here:

- https://github.com/dre0dru/editorextensions
- https://github.com/dre0dru/collections

Definitely should be reflected in the documentation or included in the release.

**Comment by deniskutovskiy** [comment]
However, this did not solve all the problems. I had to do a little more dancing to get the package to work.
Forked the repository - I will try to release a patch sometime, if Mr. Andrey does not solve the problem before then.

**Comment by dre0dru** [comment]
Sorry for not noticing earlier. Fixed in new [release](https://github.com/dre0dru/AssetManagement/releases/tag/v7.1.0), made these dependencies optional. Documentation is a little bit outdated for dependencies, will update it in some foreseeable future.
