### ISSUE TITLE
The type or namespace name 'VContainer' could not be found in AssetsLoaderExtensions.cs(6,7)

### ISSUE THREAD

**Issue by imniko** [dre0dru/AddressablesServices#4]
Getting `Library\PackageCache\com.dre0dru.assetmanagement@7.1.0\Runtime\AddressableAssets\Loaders\AssetsLoaderExtensions.cs(6,7): error CS0246: The type or namespace name 'VContainer' could not be found (are you missing a using directive or an assembly reference?)` error. 

`using VContainer;` in AssetsLoaderExtensions.cs should also be enclosed by `VCONTAINER_SUPPORT` define clause

**Comment by dre0dru** [comment]
Thanks for noticing, fixed in https://github.com/dre0dru/AssetManagement/releases/tag/v7.1.1
